name: jitpack-build

on:
  push:
    branches: [ master ]

jobs:
  jitpack:

    runs-on: ubuntu-latest

    steps:

    - name: Request master-SNAPSHOT from JitPack
      run: |
        curl -s -m https://jitpack.io/com/github/unjoinable/minigamelib/master-SNAPSHOT/
